Repository kCMI113/genie_crawler, pull requests merged in 2023-07, with the labels that each got.

#13 fix/feat: collect additional album img
  album_main.py
  concat.py
  configs/config.yaml
Labels: bug, enhancement

#14 chore: change file path using hydra
  concat.py
Labels: chore

#18 IMR-21 feat : add logging for song detail crawler
  configs/song_detail.yaml
  song_detail_main.py
  src/song_detail/song_lyrics_crawler.py
  src/song_detail_crawler.py
  src/utils.py
Labels: enhancement

#20 IMR-20 feat: implement
  album_date_main.py
  configs/album_date.yaml
  src/album_date_crawler.py
Labels: enhancement

#21 IMR-20 fix: remove album img crawling
  album_info_main.py
  configs/album_date.yaml
  src/album_info_crawler.py
Labels: enhancement

#23 IMR-23 feat : 음악 상세 정보 크롤링 좋아요 추가
  src/song_detail/song_daliy_chart_crawler.py
  src/song_detail/song_info_crawler.py
  src/song_detail/song_like_crawler.py
  src/song_detail/song_lyrics_crawler.py
  src/song_detail_crawler.py
  src/utils.py
Labels: enhancement

#25 IMR-24 feat : replace selenium to requests
  src/album_info_crawler.py
Labels: enhancement

#26 IMR-62 fix : 음악 상세정보 크롤링 오류 수정
  song_detail_main.py
  src/song_detail/song_daliy_chart_crawler.py
  src/song_detail/song_like_crawler.py
  src/utils.py
Labels: bug

#27 IMR-78 fix : 음악 상세 정보 크롤링 장르 못가져오는 오류 수정
  src/song_detail/song_info_crawler.py
Labels: bug
