Repository kCMI113/genie_crawler, pull requests merged in 2023-06, with the labels that each got.

#3 chore: setting for project
  .gitignore
  .giuhub/ISSUE_TEMPLATE/BUG.md
  .giuhub/ISSUE_TEMPLATE/CHORE.md
  .giuhub/ISSUE_TEMPLATE/DOCS.md
  .giuhub/ISSUE_TEMPLATE/FEAT.md
  .giuhub/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  README.md
  main.py
  pyproject.toml
  requirements.txt
  src/crawler.py
  src/utils.py
Labels: ci/cd

#4 feat: add some method related with saving song csv
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/CHORE.md
  .github/ISSUE_TEMPLATE/DOCS.md
  .github/ISSUE_TEMPLATE/FEAT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  main.py
  requirements.txt
  src/crawler.py
  src/utils.py
Labels: enhancement

#5 feat: create playlist csv file
  .gitignore
  README.md
  configs/config.yaml
  main.py
  requirements.txt
  src/crawler.py
  src/utils.py
Labels: enhancement

#6 feat: add headless option
  src/crawler.py
  src/utils.py
Labels: enhancement

#7 fix: debug str to int error
  src/crawler.py
Labels: bug
